# Generated by Django 4.2.3 on 2023-07-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_alter_ordemservicoitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'ordering': ('-pk',), 'verbose_name': 'ordem de serviço',
                     'verbose_name_plural': 'ordens de serviço'},
        ),
    ]
